<?php

namespace Blog\ModelBundle\Repository;

/**
 * TagToPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagToPostRepository extends \Doctrine\ORM\EntityRepository
{
}
